'''
Q1. What is Swagger UI in FastAPI?
A.
Swagger UI is an automatically generated, interactive API documentation page.
It lets you see, test, and understand your API directly from the browser.
FastAPI creates it for you without extra code.
'''
# Example:
# Run server:
# uvicorn main:app --reload
# Open browser:
# http://127.0.0.1:8000/docs


'''
Q2. How does FastAPI generate Swagger UI automatically?
A.
FastAPI reads your route decorators, function definitions,
and (later) type hints to build API documentation.
You do not write Swagger code manually.
'''
# Example:
# @app.get("/")
# def read_root():
#     return {"message": "Hello"}
# This alone appears in Swagger UI as a GET / endpoint


'''
Q3. What can you do inside Swagger UI?
A.
You can:
- See all available endpoints
- See HTTP methods (GET, POST, etc.)
- Click "Try it out"
- Send real requests
- View live JSON responses
'''
# Example:
# Open /docs
# Click GET /
# Click "Try it out"
# Click "Execute"
# See response {"message": "Hello FastAPI"}


'''
Q4. Why is Swagger UI extremely useful for beginners?
A.
Because it removes the need for tools like Postman at the start.
You can learn APIs visually and interactively inside the browser.
'''
# Example:
# Beginner workflow:
# Write route → refresh /docs → test immediately


'''
Q5. Why is Swagger UI valuable for teams and other developers?
A.
Because anyone can understand and test your API instantly.
It acts as live, always-up-to-date documentation.
'''
# Example:
# Share API URL
# Other dev opens /docs
# They immediately know how to use your API


'''
Q6. What is ReDoc and how is it different from Swagger UI?
A.
ReDoc is another documentation page generated by FastAPI.
It is cleaner and read-only, mainly used for formal documentation.
Swagger UI is better for learning and testing.
'''
# Example:
# Swagger UI → http://127.0.0.1:8000/docs
# ReDoc       → http://127.0.0.1:8000/redoc
 